### ISSUE TITLE
missing event information

### ISSUE THREAD

**Issue by Joppla** [dkniffin/webtrees-openstreetmap#21]
Nice tool, definitely better than everything from Google :-)

But: If you click on a place-marker you see an event date, but not the related person. 
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22486200/d77bf38a-e808-11e6-9882-4ee82a7b7cb2.png)

Should be nice I you can click on the date or the person.

**Comment by dkniffin** [comment]
Yea, I definitely had plans to add more to that bubble. If you're interested in making a PR for this, I'd be happy to review and merge it.

**Comment by dkniffin** [comment]
The change would go [here](https://github.com/dkniffin/webtrees-openstreetmap/blob/6673c3603e7c7df341a915542291738994ea5cf9/module.php#L257). Instead of `$event->shortSummary()`, which [returns a one-line description of the event](https://github.com/dkniffin/webtrees-openstreetmap/blob/e4837d97547c27117ffb7bfadef792509f060881/classes/FactPlace.php#L65), we'd make something like a `longSummary` or something, which returned a little more data, with links and whatnot.

**Comment by Joppla** [comment]
Is the `longSummary()` anywhere defined yet? It seems me not. 

The `shortSummary()` is taken from 
```
// Return a one line summary from the fact
	public function shortSummary() {
		return $this->fact->summary();
	}
```
But where is `$this->fact->summary();` defined?

**Comment by Joppla** [comment]
Hmmm, `summary()` is a webtrees function. It give only the summary of the event. All information is in `$this->fact`, but how to get it out of there?

**Comment by dkniffin** [comment]
Yea, `summary()` is a webtrees function defined [here](https://github.com/fisharebest/webtrees/blob/master/app/Fact.php#L377). It looks like they don't have another good method that has all the info like we want it, so we'll have to put it together ourselves, by having the new `longSummary()` (which is not defined yet, but should go right below `shortSummary()`) call the other methods in that `Fact.php` file. For example, if we want to get the date, we'd do `$this->fact->getDate()`, which is defined [here](https://github.com/fisharebest/webtrees/blob/master/app/Fact.php#L203)

**Comment by Joppla** [comment]
`summary()` gives sufficient information, I think. What we need is name of the person, the id of the person and (if possible) the relation to the main person. This we can add to the longSummary. 

In fact.php aren't functions that can generate that information, what I see.

**Comment by Joppla** [comment]
PS. Am I correct that the "Spouse"-events aren't shown on the map?

**Comment by dkniffin** [comment]
Yea, that looks like a good way to do it. Not sure what you mean by "Spouse"-events. It should be showing events that happen to the person, their parents, their siblings, their children, and their spouses.

**Comment by Joppla** [comment]
Maybe later further research

**Comment by Joppla** [comment]
I think, the easiest way is to add the needed information to the array $events, something like:
	```
	# Map each person to their facts
		foreach($people as $person) {
			$xref = $person->getXref();
			$fullNN = $person->getAllNames()[0]['fullNN'];
			$events[$xref] = array();
			foreach($person->getFacts() as $fact) {
				$placefact = new \FactPlace($fact);
				array_push($events[$xref], $placefact, $fullNN);
				if ($placefact->knownLatLon()) $geodata = true;
			}
```
But I m not sure if the `array_push` is correct. If this works, you have to unpack the name in the `drawMap()`.

If this works it must be also  possible to add the other information, the relation to the original person, in `$events` imo.

**Comment by Joppla** [comment]
Is it correct that the data will be two times sorted, in line [#171](https://github.com/dkniffin/webtrees-openstreetmap/blob/master/module.php#L171) and [#248](https://github.com/dkniffin/webtrees-openstreetmap/blob/master/module.php#L248). It seems me overdone.

**Comment by dkniffin** [comment]
Yea, I think you're right about the double sort. Good catch!

I'll work on getting this added to the code sometime today.

**Comment by Joppla** [comment]
Maybe you have an idea to add also the relation to the main person to this array? I cannot find out how. Should be nice if see something like:
```
Boris Johnson, sun of Boris Johnson sr.
born at 1 januari 1900 in Ugwambibi
```

**Comment by Joppla** [comment]
With:
`echo I18N::translate('Son');`
you will get "Sun" in every language.

With `$parent->getSex()` you will get "M" or "F" (or "U" for un defined). So you will know who is the father and who is the mother. But you test it also with:
`if ($parent==$family->getWife())` or `if ($parent==$family->getHusband())`

I think you have to define immediately in the array $people the relation to $thisPerson. Maybe even with the related $XRef:
```
if ($parent==$family->getHusband()){
  $relation="Father";
  } else {
  $relation="Mother";
  }
$Xref = $person->getXref();
$people[$Xref] = array('relation'=>$relation, 'fullName'=>$parent->getAllNames()[0]['fullNN']);
```

**Comment by Joppla** [comment]
Maybe with: 
```
foreach ($family->getFacts() as $fact){
	$placefact = new \FactPlace($fact);
	echo $placefact->shortSummary(); //only test what information is in.
}
```
we can add the information ass marriages in the map ...

**Comment by Joppla** [comment]
Please merge the fork, I added links and info to the pop-ups.
