### ISSUE TITLE
missing Spouse

### ISSUE THREAD

**Issue by Joppla** [dkniffin/webtrees-openstreetmap#23]
Am I correct that the "Spouse"-events aren't shown on the map? On my map I don't see the Spouse, but in module.php , lin #145 the events should be extracted.

**Comment by dkniffin** [comment]
Yea, it should show the spouse's events. If it's not, I think it's a bug.

**Comment by Joppla** [comment]
It seems me a bug.

**Comment by Joppla** [comment]
And Siblings are also not shown.

**Comment by dkniffin** [comment]
Is it showing parents and children?

**Comment by Joppla** [comment]
Yes. It does

**Comment by dkniffin** [comment]
Hmm. Would you mind trying to change [this line](https://github.com/dkniffin/webtrees-openstreetmap/blob/master/module.php#L139) to`if ($child !== $thisPerson) {` and seeing if siblings show up?

**Comment by Joppla** [comment]
I will do tomorrow.

**Comment by Joppla** [comment]
Line 139 has to be: 				`if ( $child !== $thisPerson) {`
Line 148 has to be: 				`if ( $spouse !== $thisPerson) {`
