### ISSUE TITLE
OSM doesn't show map for person

### ISSUE THREAD

**Issue by Joppla** [dkniffin/webtrees-openstreetmap#25]
I find out that the OSM map not is shown (white field) at my site when the person is born before 1917. Maybe something with privileges?
born in 1918:
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22593794/9e0e26da-ea20-11e6-9655-ad892324cf25.png)
born in 1916:
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22593829/bf44cfc0-ea20-11e6-940f-3a4ba2607e63.png)

**Comment by dkniffin** [comment]
@Joppla Are you logged in when you take these screenshots?

**Comment by Joppla** [comment]
This is when I'm logged in. When I m logged out, there is no map data, but that seems me correct:
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22593982/6a2cff16-ea21-11e6-92fa-6b42fa701412.png)

**Comment by dkniffin** [comment]
Ok. Mind checking your browser console for errors on the 1916, logged in one?

**Comment by Joppla** [comment]
I don't understand, what your question is.

**Comment by dkniffin** [comment]
The browser console is the place where the browser logs errors. You can find the instructions for opening it in firefox [here](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) and in chrome [here](http://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome)

**Comment by Joppla** [comment]
See above. From testing I know that if there is any mistake in the javascript code for leaflet you will get immediately a white screen.

**Comment by Joppla** [comment]
I find out that it is not connected to the year 1917. Other persons give other results. Strange.

**Comment by Joppla** [comment]
I will do today an update, but it seems me that there are more and more white screens. Even at persons they were working well before yesterday.

**Comment by Joppla** [comment]
The new 1.8 version give still a white screen. In the console there are the following messages:
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22618817/cd0d20e6-eae6-11e6-86e1-9071050a2756.png)
Where can I find a 1.7 version? I like to test when it went wrong.

**Comment by Joppla** [comment]
I replaced the original 1.7 version. This version shows the maps correct.

**Comment by dkniffin** [comment]
Can you get it to consistently happen for one person, or is it random whether it happens or not?

**Comment by Joppla** [comment]
It seems me consistently. But .... what happen with the color_i when there are more people than colors? Because one of the changes was that we added sibblings and spouces to the map, so more people, so more colors needed ... Maybe that generate the error in leaflet. The white screen is for me typical an error in the code for leaflet.

**Comment by Joppla** [comment]
With deleting the line color_i++ it seems me working (with all markers in the same color) :-)

**Comment by dkniffin** [comment]
Ah, yep. Good catch. Try changing [this line](https://github.com/dkniffin/webtrees-openstreetmap/blob/master/module.php#L271) to `$color_i = ($color_i + 1) % count($colors);`

**Comment by Joppla** [comment]
That works correct!
It should be maybe nice to use different scale of colors for parents, sibblings and children.
fe:
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/22621181/82ddad92-eb1d-11e6-81a4-2afc75c90c58.png)
parents in the 3rd / 4th row from under, self, spouse and siblings the middle row and children the lowest. But there are many possibilities. What do you think?

**Comment by Joppla** [comment]
please, can you look to issue [#24](https://github.com/dkniffin/webtrees-openstreetmap/issues/25)
